@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.hero.witchery_rewitched.block;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;