@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.hero.witchery_rewitched.block.witch_oven;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;